### ISSUE TITLE
安装出现报错

### ISSUE THREAD

**Issue by chenchen-eng** [CharlesPikachu/musicdl#11]
Using cached https://files.pythonhosted.org/packages/88/7f/740b99ffb8173ba9d20eb890cc05187677df90219649645aca7e44eb8ff4/pycryptodome-3.10.1.tar.gz
    Complete output from command python setup.py egg_info:
    Testing support for clang
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
        return self.find_available_vc_vers()[-1]
    IndexError: list index out of range

**Comment by CharlesPikachu** [comment]
直接下载源码安装试试？
