### ISSUE TITLE
可以用哎，就是我不太会用，怎么指定来源进行下载呢

### ISSUE THREAD

**Issue by xiaoxiao12138xiaoxiao** [CharlesPikachu/musicdl#13]

**Comment by yoyoyoqiekenao** [comment]
好像是这个target_srcs  ，你可以一个个看看  代码拉下来就能直接运行的

**Comment by CharlesPikachu** [comment]
默认是从这几个源来搜索的：
`target_srcs = [
    'baiduFlac', 'kugou', 'kuwo', 'qq', 'qianqian', 
    'netease', 'migu', 'xiami', 'joox', 'yiting',
]`
根据提示选择匹配的歌曲下载就可以了
