### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by andfaraway** [CharlesPikachu/musicdl#16]
**Environment (使用环境)**

- Installation method (安装方式):  python3 setup.py install
- The version of musicdl (版本号): 最新版本
- Operating system (操作系统): macos Monterey 12.2.1
- Python version (Python版本): 3.10.1

**Question description (问题描述)**
安装报错，我安装GAME的项目也是报相同的错误，然后网上搜了好久也没有解决，需要大佬支持~

**Screenshot (报错截图)**
![WX20220308-165929](https://user-images.githubusercontent.com/20471572/157203043-860ce5c5-a6b0-4b86-be70-b17106b293b4.png)
**Advice (修复建议)**

**Comment by CharlesPikachu** [comment]
你直接pip安装试试呢？在终端执行 `pip install musicdl`，或者你可以先手动安装prettytable，再安装这个包

**Comment by andfaraway** [comment]
可以跑起来了，感谢~
