### ISSUE TITLE
[BUG] 写入log文件，中文编码为GBK

### ISSUE THREAD

**Issue by lingr7** [CharlesPikachu/musicdl#18]
**Environment (使用环境)**

- Installation method (安装方式): pycharm 社区版根据setup.py创建venv环境运行
- The version of musicdl (版本号): 2.3.2
- Operating system (操作系统): win10
- Python version (Python版本): 3.8

**Question description (问题描述)**
musicdl/modules/utils/logger.py中，将log写入文件，写入中文时，使用的是GBK 编码，如何指定为UTF-8编码？

```python
    def info(self, message, disable_print=False):
        if disable_print:
            fp = open(self.logfilepath, 'a')
            fp.write(message + '\n')
        else:
            Logger.log(logging.INFO, message)
```
**Screenshot (报错截图)**
![image](https://user-images.githubusercontent.com/37898999/162662259-123038ee-e839-4362-ad71-42371aa7c54e.png)

**Advice (修复建议)**
添加指定编码的选项或参数。

**Comment by AlieZVzz** [comment]
fp = open(self.logfilepath, 'a', encoding="utf-8")

**Comment by lingr7** [comment]
测试过，未生效。

**Comment by CharlesPikachu** [comment]
第三十七行：
`logging.FileHandler(logfilepath, encoding='utf-8')`
指定一下编码为utf-8

**Comment by lingr7** [comment]
![image](https://user-images.githubusercontent.com/37898999/172274020-9e927f8f-5fbd-4311-b608-393a79723f03.png)
已经生效，就是这个esc的有点别扭。
