### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by florinsdistortedvision** [CharlesPikachu/musicdl#21]
**Environment (使用环境)**

- Installation method (安装方式): 
- The version of musicdl (版本号): 
- Operating system (操作系统): 
- Python version (Python版本): 

**Question description (问题描述)**

**Screenshot (报错截图)**

**Advice (修复建议)**

I have installed pycryptodome via pip and still the same error shows

**Comment by RimoChan** [comment]
咦，等等，这个是怎么解决的？
