### ISSUE TITLE
[BUG] Netease querying not working

### ISSUE THREAD

**Issue by StayBlue** [CharlesPikachu/musicdl#27]
**Environment (使用环境)**
Windows 10

- Installation method (安装方式): 
pip install git+https://github.com/CharlesPikachu/musicdl.git@master
- The version of musicdl (版本号): 
2.3.5
- Operating system (操作系统): 
Windows 10
- Python version (Python版本): 
3.9.7
**Question description (问题描述)**
I tried searching for a song on Netease, but nothing appeared.

**Comment by CharlesPikachu** [comment]
how about trying other keywords to search?
![image](https://user-images.githubusercontent.com/36195560/219845511-b6e67816-1062-4966-80ab-614fa0771604.png)
my test is ok
