### ISSUE TITLE
老哥, 建议兼容下Mac.  很多类型错误

### ISSUE THREAD

**Issue by ytx0574** [CharlesPikachu/musicdl#4]
[wangyiyun-INFO]: 请输入歌曲名 --> "我"
<Warning>--未检索到歌曲的相关信息, 请重新输入--<Warning>
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Users/johnson/Downloads/Music-Downloader-master/MusicDownloader/cmd.py", line 136, in <module>
    MusicDownloader().run()
  File "/Users/johnson/Downloads/Music-Downloader-master/MusicDownloader/cmd.py", line 54, in run
    num_downed, num_need_down = self.__userSearch()
TypeError: 'NoneType' object is not iterable

**Comment by CharlesPikachu** [comment]
我现在手边没Ｍａｃ
你可以尝试一下利用ｐｉｐ安装成库之后运行。。。ＲＥＡＤＭＥ里有示例代码。

**Comment by CharlesPikachu** [comment]
现在应该可以了，之前有行代码写错了，所以出现了该BUG。

**Comment by ytx0574** [comment]
MeiZu-16th:Music-Downloader-master johnson$ cd MusicDownloader/
MeiZu-16th:MusicDownloader johnson$ python cmd.py 
  File "cmd.py", line 3
SyntaxError: Non-ASCII character '\xe9' in file cmd.py on line 4, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

不. MacOS上是中文编码类型上的BUG.

**Comment by CharlesPikachu** [comment]
因为MAC默认是py2

**Comment by greenlaw110** [comment]
试了一下，macOS 和 Linux 都有这个问题，请问可以如何解决吗？

**Comment by CharlesPikachu** [comment]
发下具体的截图，环境等信息，我这边Linux和mac都测了下，都可以正常使用

**Comment by CharlesPikachu** [comment]
自己在头部声明一下编码？`# coding=utf-8`

**Comment by greenlaw110** [comment]
我试过 [这个](https://stackoverflow.com/questions/21639275/python-syntaxerror-non-ascii-character-xe2-in-file) SO 的一个办法:
<img width="733" alt="image" src="https://user-images.githubusercontent.com/216930/154918962-24cf46d6-366c-4378-929e-45dbfd679881.png">

不过要改的文件不只 `musicdl.py`，还有其他文件也要改，而起都改了之后貌似还有其他问题

**Comment by greenlaw110** [comment]
这个也是一个问题：
<img width="643" alt="image" src="https://user-images.githubusercontent.com/216930/154919388-829abc10-648c-4a03-9329-b23f34278bc9.png">

我这里需要把 `f` 拿掉才行

**Comment by CharlesPikachu** [comment]
把python升级到3.6 or 更高的版本

**Comment by greenlaw110** [comment]
用 python3 的情况：
<img width="1052" alt="image" src="https://user-images.githubusercontent.com/216930/154920718-222b9d00-d190-4aa6-8c3f-a0fcdea45e49.png">
