### ISSUE TITLE
现在QQ,Qianqian,baiduFlac是不是用不了了?

### ISSUE THREAD

**Issue by gameboyring** [CharlesPikachu/musicdl#9]
qq是搜索之后的下载地址都不正确了
qianqian和baiduFlac是无法搜索

**Comment by CharlesPikachu** [comment]
I will check this problem in recent days.

**Comment by CharlesPikachu** [comment]
我刚刚测试了，QQ音乐是正常的，其他两个我会在升级的版本中修复
